// Configuration client — demenageur-template
// Modifier les valeurs ci-dessous pour personnaliser le site

export const clientConfig = {
  NOM_ENTREPRISE: "TransLog Pro",
  NOM_LEGAL: "TRANSLOG PRO SARL",
  SIRET: "000 000 000",
  METIER: "transporteur",
  METIER_LABEL: "Transporteur",
  GENRE_DIRIGEANT: "M",
  PRENOM_DIRIGEANT: "Jean",
  NOM_DIRIGEANT: "Dupont",
  ANNEE_CREATION: "2000",
  ANNEES_EXPERIENCE: "25",
  TELEPHONE: "+33 1 42 60 11 22",
  EMAIL: "contact@translogpro.fr",
  ADRESSE: "14 Rue de la Paix",
  CODE_POSTAL: "75001",
  VILLE: "Paris",
  DEPARTEMENT: "Paris",
  REGION: "Ile-de-France",
  COMMUNE_1: "Nanterre",
  COMMUNE_2: "Cergy",
  COMMUNE_3: "Rouen",
  FONDATEUR_NOM: "Pierre Dupont",
  PAYS: "France",
  HORAIRES: "Lun-Ven: 9h00-12h00 / 14h00-18h00",
  ZONE_INTERVENTION: "Paris et Ile-de-France",
  LATITUDE: "48.8566",
  LONGITUDE: "2.3522",
  DOMAINE: "www.translogpro.fr",
  META_TITLE: "TransLog Pro | Transporteur Routier de Fret — Paris & Ile-de-France",
  META_DESCRIPTION: "TransLog Pro — transporteur routier de fret depuis Paris depuis 2000. Transport interurbain, logistique, affretement, transport europeen. Devis sous 2h.",
  META_KEYWORDS: "transporteur paris, transport routier ile-de-france, fret paris, affretement ile-de-france, logistique paris, translog pro",
  SLOGAN: "Votre fret, notre fiabilite.",
  ACCROCHE_HERO: "Transport Routier — Paris & Ile-de-France",
  DESCRIPTION_ENTREPRISE: "Depuis 2000, TransLog Pro assure le transport routier de fret en Ile-de-France et sur les axes nationaux avec rigueur et ponctualite.",
  DESCRIPTION_FOOTER: "Depuis 2000, TransLog Pro assure le transport routier de fret, la logistique et l'affretement depuis Paris vers toute la France et l'Europe. Devis en 2h, livraison garantie.",
  DESCRIPTION_APROPOS: "Fondee par Pierre Dupont, l'entreprise est nee d'une passion pour le transport et la logistique.",
  GOOGLE_MAPS_URL: "",
  FACEBOOK_URL: "https://facebook.com/translogpro",
  INSTAGRAM_URL: "https://instagram.com/translogpro",
  LINKEDIN_URL: "https://linkedin.com/company/translog-pro",
  N8N_WEBHOOK: "",
  ADMIN_PASSWORD: "1234",
} as const;

export type ClientConfigKey = keyof typeof clientConfig;
