// Configuration client — demenageur-template
// Modifier les valeurs ci-dessous pour personnaliser le site

export const clientConfig = {
  NOM_ENTREPRISE: "Transports Boulocher",
  NOM_LEGAL: "TRANSPORTS BOULOCHER SARL",
  SIRET: "425 083 508",
  METIER: "demenageur",
  METIER_LABEL: "Transporteur",
  GENRE_DIRIGEANT: "M",
  PRENOM_DIRIGEANT: "Christophe",
  NOM_DIRIGEANT: "Boulocher",
  ANNEE_CREATION: "1999",
  ANNEES_EXPERIENCE: "25",
  TELEPHONE: "+33 6 42 08 70 60",
  EMAIL: "direction@transportsboulocher.fr",
  ADRESSE: "Chaussee de la Moselle",
  CODE_POSTAL: "76600",
  VILLE: "Le Havre",
  DEPARTEMENT: "Seine-Maritime",
  REGION: "Normandie",
  PAYS: "France",
  HORAIRES: "Lun-Ven: 9h00-12h00 / 14h00-18h00",
  ZONE_INTERVENTION: "Le Havre et Normandie",
  LATITUDE: "49.4844",
  LONGITUDE: "0.1079",
  DOMAINE: "www.transportsboulocher.fr",
  META_TITLE: "Transports Boulocher | Transporteur Routier Fret — Le Havre & Normandie",
  META_DESCRIPTION: "Transports Boulocher — transporteur routier de fret depuis Le Havre depuis 1999. Transport interurbain, logistique, affretement, transport europeen. Devis sous 2h.",
  META_KEYWORDS: "transporteur le havre, transport routier normandie, fret seine-maritime, affretement normandie, logistique le havre, transports boulocher",
  SLOGAN: "Votre fret, notre fiabilite.",
  ACCROCHE_HERO: "Transport Routier — Le Havre & Normandie",
  DESCRIPTION_ENTREPRISE: "Depuis 1999, Transports Boulocher assure le transport routier de fret en Normandie et sur l'axe Le Havre-Paris avec rigueur et ponctualite.",
  DESCRIPTION_FOOTER: "Depuis 1999, Transports Boulocher assure le transport routier de fret, la logistique et l'affretement depuis Le Havre vers toute la France et l'Europe. Devis en 2h, livraison garantie.",
  DESCRIPTION_APROPOS: "Fondee par Christophe Boulocher, l'entreprise est nee d'une passion pour le transport et la logistique.",
  GOOGLE_MAPS_URL: "",
  FACEBOOK_URL: "https://facebook.com/transportsboulocher",
  INSTAGRAM_URL: "https://instagram.com/transportsboulocher",
  LINKEDIN_URL: "https://linkedin.com/company/transports-boulocher",
  N8N_WEBHOOK: "",
  ADMIN_PASSWORD: "1234",
} as const;

export type ClientConfigKey = keyof typeof clientConfig;
